version: '3.8'

services:
  postgres:
    image: postgres:13  # Usa la versión de PostgreSQL que prefieras
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"  # Expone el puerto 5432 al host
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
